language: cpp

compiler:
  - gcc

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libstdc++6
env: COMPILER=g++-5


before_install:
  - bash ./CI/Travis/install.sh

script:
  - bash ./CI/Travis/build.sh
  - bash ./CI/Travis/test.sh

