require "Macaroni.IO.GeneratedFileWriter";
require "Macaroni.Model.Library";
require "Macaroni.IO.Path";

function getIncludePath()
	local path, err = pcall(function()
		return properties.lua["5.1.4"].include;
	end);
	if (err ~= nil) then
		error([[Could not find variable properties.lua["5.1.4"].include.]]);
	end
	return path;
end

function Prepare(library, sources, outputPath, installPath, extraArgs)
	local includePath = getIncludePath();	
	local buildjam = outputPath:NewPath("/jamroot.jam");
	print("Creating Boost.Build file at " .. buildjam.AbsolutePath .. ".");
	local writer = buildjam:CreateFile();			
	
	writer:Write([[
# Generated by Macaroni.

import boost ;
import path ;

project
	:	usage-requirements
		<include>]] .. includePath .. [[
	;
	
alias libSources
	:	
	;
	]]);
    writer:Close();    
end

