-- Final Manifest generated by Macaroni

id =
{
    group    = [[Macaroni]],
    name     = [[Lua]],
    version  = [[5.1.4]]
}

description = [[Lua library compiled as C++]]

sources=
{
    [[Mh]],
}


function prepare()
end
