require "Macaroni.Model.Library";
require "Macaroni.IO.Path";

print("HEELLEELELEO!");

function Generate(library, path)
    print "Generating build.jam for the Generated source.\n";
    local buildjam = path:NewPath("/build.jam");
    print("Opening " .. buildjam.AbsolutePath .. "\n");
    local writer, errorMsg, errorNumber = io.open(buildjam.AbsolutePath, 'w+');
    if (writer == nil) then
        error(tostring(errorNumber) .. " " .. errorMsg, 2);
    end
    writer:write([[
# Generated by Jam Generator.
alias generated
	:	[ glob-tree *.c	: .svn ]
		[ glob-tree *.cpp	: .svn ]
	:	<include>./
		<include>../Source
	;
    ]]);
end
